name 'mongodb_tu'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mongodb_tu'
long_description 'Installs/Configures mongodb_tu'
version '0.1.0'
